server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: admin
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true


